[package]
name = "example"
cairo-version = ">=2.13.1"
# version.workspace = true
# edition.workspace = true
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
mint_character = "./scripts/mint_character.sh"
cash_faucet = "./scripts/cash_faucet.sh"

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
  "dojo::world::world_contract::world",
]

[dependencies]
starknet = ">=2.13.1"
dojo = "1.8.0"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
# nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", tag = "v1.2.0"}
nft_combo = { path = "../packages/nft_combo" }

[dev-dependencies]
cairo_test = ">=2.13.1"
dojo_cairo_test = "1.8.0"
