[package]
name = "example"
cairo-version = ">=2.12.2"
# version.workspace = true
# edition.workspace = true
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
mint_character = "./scripts/mint_character.sh"
cash_faucet = "./scripts/cash_faucet.sh"

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
  "dojo::world::world_contract::world",
]

[dependencies]
starknet = ">=2.12.2"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
# nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", tag = "v1.1.0"}
nft_combo = { path = "../packages/nft_combo" }

[dev-dependencies]
cairo_test = ">=2.12.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0" }
