[package]
name = "example"
version.workspace = true
edition.workspace = true
cairo-version = "=2.9.4"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
mint_character = "./scripts/mint_character.sh"
cash_faucet = "./scripts/cash_faucet.sh"

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
  "dojo::world::world_contract::world",
]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
# nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", tag = "v1.0.0"}
nft_combo = { path = "../packages/nft_combo" }

[dev-dependencies]
cairo_test = "=2.9.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.4.0" }


#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]
