[workspace]
members = [
  "packages/nft_combo",
  "example",
]
description = "Dojo erc721 combo library"
homepage = "https://github.com/underware-gg/cairo-nft-combo"
cairo-version = "2.9.2"

[workspace.package]
version = "0.2.0"
edition = "2024_07"

[workspace.dependencies]
starknet = "2.9.2"
cairo_test = "2.9.2"

[workspace.tool.fmt]
sort-module-level-items = true
